name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  video_player:
  sqflite:
  path:
  keyboard_dismisser:
  keyboard_attachable: ^1.0.0
  json_annotation: ^3.0.0
  basic_utils: ^2.5.3
  string_scanner: ^1.0.5
  crypto: ^2.1.4
  webview_flutter:
  device_info:

  firebase_auth:
  firebase_database:
  cloud_firestore:
  firebase_analytics:
  firebase_storage:
  google_maps_flutter: ^0.5.27+1

  cupertino_icons: ^0.1.3
  # Remote API
  http: ^0.12.0+4
  connectivity: ^0.4.8+2
  intl: ^0.16.1
  font_awesome_flutter: ^8.7.0
  fluttertoast: ^3.1.0
  flutter_bloc:
  equatable: ^1.1.1
  data_connection_checker: ^0.3.4
  shimmer: ^1.0.1
  cached_network_image: ^2.0.0
  auto_size_text: ^2.1.0
  logging: ^0.11.4
  rxdart:
  scoped_model: ^1.0.1
  flutter_redux: ^0.6.0
  provider: 
  kiwi: ^0.2.0
  # Service locator
  get_it: ^4.0.1
  # Functional programming thingies
  dartz: ^0.9.0-dev.5
  # Local cache
  shared_preferences: ^0.5.6+3
  dio: ^3.0.9

  image_picker: ^0.6.1+4
  flutter_image_compress: ^0.6.3
  path_provider: ^1.2.0
  uuid: ^2.0.2
  image_cropper: ^1.1.0
  animator: ^1.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  e2e: "^0.2.0"
  pedantic: ^1.8.0
  flutter_launcher_icons: "^0.7.3"
  build_runner:
  json_serializable: ^3.2.0
  kiwi_generator: ^0.4.0
  mockito: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/icons/
    - assets/
    - assets/img/
    - assets/solitaire/
    - assets/items.json
    - assets/pokemons.json
    - assets/images/
    - assets/config/
    - assets/taxi/
    - assets/images/scratch/

  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
          weight: 400
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.otf

    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.otf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.otf
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
