name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # Remote API
  http: ^0.12.0+4
  connectivity: ^0.4.8+2
  intl: ^0.16.1
  font_awesome_flutter: ^8.7.0
  google_maps_flutter: ^0.5.24+1
  fluttertoast: ^3.1.0
  flutter_bloc: ^2.0.0
  equatable: ^1.1.0
  data_connection_checker: ^0.3.4
  shimmer: ^1.0.1
  cached_network_image: ^2.0.0
  auto_size_text: ^2.1.0
  logging: ^0.11.4
  rxdart: ^0.22.0
  scoped_model: ^1.0.1
  flutter_redux: ^0.6.0
  provider: ^3.1.0+1
  kiwi: ^0.2.0
  # Service locator
  get_it: ^4.0.1
  # Functional programming thingies
  dartz: ^0.9.0-dev.5
  # Local cache
  shared_preferences: ^0.5.6+3
  cloud_firestore: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  build_runner:
  kiwi_generator: ^0.4.0
  mockito: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/icons/
    - assets/
    - assets/img/
    - assets/solitaire/
    - assets/items.json
    - assets/pokemons.json
    - assets/images/

  fonts:
    - family: Boxicons
      fonts:
        - asset: fonts/boxicons.ttf
          weight: 400
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.otf

    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.otf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf

    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.otf
